---
apiVersion: v1
kind: Service
metadata:
  name: gfs-dataset
  namespace: training
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gfs-dataset
  namespace: training
subsets:
  - addresses:
      - ip: 10.196.50.147
    ports:
      - port: 1
  - addresses:
      - ip: 10.196.50.212
    ports:
      - port: 1
